import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion"; // Added AnimatePresence
import {
  ArrowLeft,
  Phone,
  MapPin,
  Briefcase,
  Award,
  Share2,
  Heart,
  CheckCircle,
  ChevronLeft, // Added ChevronLeft
  ChevronRight, // Added ChevronRight
} from "lucide-react";

import { Loading } from "../../components/common";
import { useTranslation } from "react-i18next";
import { masteryService } from "../../services/MasteryService";
import BookingCalendar from "../../components/booking/BookingCalendar";
import { favoriteService } from "../../services/favoriteService";
import { useKeycloak } from "../../providers/KeycloakProvider";
import { useLookups } from "../../hooks/useLookups";
import { LOOKUP_TYPES, lookupLabel } from "../../utils/lookupUtils";
import ContactButton from "../../components/common/ContactButton"; // Import the ContactButton component

/* ─── PhotoImage: Renders a single photo using the full URL ── */
const PhotoImage = ({ photoUrl, alt, className, emptyLabel }) => {
  if (!photoUrl) {
    return (
      <div
        className={`${className} bg-[#f0eeeb] dark:bg-[#2d2a27] flex items-center justify-center text-[#8a8580] text-sm`}>
        {emptyLabel}
      </div>
    );
  }

  return (
    <img
      src={photoUrl} // This is now the FULL URL generated by your backend
      alt={alt}
      className={className}
      loading="lazy"
      onLoad={() => console.log("Loaded:", photoUrl)}
      onError={(e) => {
        console.error("Failed image:", photoUrl);
        e.target.src = "/placeholder.jpg";
      }}
    />
  );
};

/* ─── Image Gallery ───────────────────────────────── */
const Gallery = ({ photoUrls, photoEmptyLabel, galleryEmptyLabel }) => {
  const [current, setCurrent] = useState(0);
  const total = photoUrls ? photoUrls.length : 0; // Safety check for null/undefined

  // If there are no photos, show a clean placeholder
  if (total === 0) {
    return (
      <div className="relative overflow-hidden rounded-2xl bg-[#f0eeeb] dark:bg-[#2d2a27] aspect-[4/3] flex items-center justify-center text-[#8a8580]">
        {galleryEmptyLabel}
      </div>
    );
  }

  const prev = () => setCurrent((c) => (c - 1 + total) % total);
  const next = () => setCurrent((c) => (c + 1) % total);

  return (
    <div className="relative w-full">
      {/* Main image */}
      <div className="relative overflow-hidden rounded-2xl bg-[#f0eeeb] dark:bg-[#2d2a27] aspect-[4/3]">
        <AnimatePresence mode="wait">
          <motion.div
            key={current}
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -40 }}
            transition={{ duration: 0.3 }}
            className="w-full h-full">
            <PhotoImage
              photoUrl={photoUrls[current]}
              alt={`Photo ${current + 1}`}
              className="w-full h-full object-cover"
              emptyLabel={photoEmptyLabel}
            />
          </motion.div>
        </AnimatePresence>

        {/* Nav arrows — only if multiple photos */}
        {total > 1 && (
          <>
            <button
              onClick={prev}
              className="absolute left-3 top-1/2 -translate-y-1/2 bg-white/80 dark:bg-black/50 backdrop-blur-sm p-2 rounded-full shadow hover:scale-110 transition-transform">
              <ChevronLeft size={20} />
            </button>
            <button
              onClick={next}
              className="absolute right-3 top-1/2 -translate-y-1/2 bg-white/80 dark:bg-black/50 backdrop-blur-sm p-2 rounded-full shadow hover:scale-110 transition-transform">
              <ChevronRight size={20} />
            </button>

            {/* Counter badge */}
            <span className="absolute bottom-3 right-3 bg-black/50 text-white text-xs px-2.5 py-1 rounded-full backdrop-blur-sm">
              {current + 1} / {total}
            </span>
          </>
        )}
      </div>

      {/* Thumbnails — only if multiple photos */}
      {total > 1 && (
        <div className="flex gap-2 mt-3 overflow-x-auto pb-1">
          {/* Fixed: Changed 'id' to 'url' so it correctly passes the full URL */}
          {photoUrls.map((url, i) => (
            <button
              key={url}
              onClick={() => setCurrent(i)}
              className={`flex-shrink-0 w-16 h-16 rounded-xl overflow-hidden border-2 transition-all ${
                i === current
                  ? "border-[#6d2842] scale-105"
                  : "border-transparent opacity-60 hover:opacity-100"
              }`}>
              <PhotoImage
                photoUrl={url}
                alt={`Thumb ${i + 1}`}
                className="w-full h-full object-cover"
                emptyLabel={photoEmptyLabel}
              />
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

/* ───────────────────────────────────────────── */
/* Badge & InfoRow (Unchanged) */
/* ───────────────────────────────────────────── */
const Badge = ({ children, color = "default" }) => {
  const colors = {
    default:
      "bg-[#f0eeeb] dark:bg-[#3a3633] text-[#5d5955] dark:text-[#c4bfb9]",
    green:
      "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-400",
    primary:
      "bg-[#6d2842]/10 text-[#6d2842] dark:bg-[#6d2842]/30 dark:text-[#e8a0b4]",
  };

  return (
    <span
      className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full ${colors[color]}`}>
      {children}
    </span>
  );
};

const InfoRow = ({ label, value }) => (
  <div className="flex justify-between items-center py-3 border-b border-[#e8e7e5] dark:border-[#3a3633] last:border-0">
    <span className="text-sm text-[#8a8580] dark:text-[#7a756f]">{label}</span>
    <span className="text-sm font-medium text-[#2d2a27] dark:text-[#e8e4e0]">
      {value}
    </span>
  </div>
);

/* ───────────────────────────────────────────── */
/* Main Component */
/* ───────────────────────────────────────────── */
const MasteryInfos = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { t } = useTranslation();

  const [mastery, setMastery] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isLiked, setIsLiked] = useState(false);
  const [favLoading, setFavLoading] = useState(false);
  const { authenticated, login } = useKeycloak();
  const { lookups } = useLookups();

  useEffect(() => {
    setLoading(true);
    masteryService
      .getMasteryById(id)
      .then(setMastery)
      .catch((err) =>
        setError(err?.message ?? t("masteryInfo.failedToLoad"))
      )
      .finally(() => setLoading(false));
  }, [id]);

  useEffect(() => {
    if (!authenticated || !id) return;
    favoriteService
      .statusMastery(id)
      .then((res) => setIsLiked(Boolean(res.data?.favorited)))
      .catch(() => setIsLiked(false));
  }, [authenticated, id]);

  const handleToggleFavorite = async () => {
    if (!authenticated) {
      login();
      return;
    }
    if (favLoading) return;
    setFavLoading(true);
    try {
      const res = await favoriteService.toggleMastery(mastery.id);
      setIsLiked(Boolean(res.data?.favorited));
    } finally {
      setFavLoading(false);
    }
  };

  if (loading) return <Loading text={t("masteryInfo.loading")} />;

  if (error) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-4">
        <p className="text-[#6d2842] font-medium">{error}</p>
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-sm underline">
          <ArrowLeft size={16} /> {t("common.goBack")}
        </button>
      </div>
    );
  }

  const typeLabel = lookupLabel(
    lookups,
    LOOKUP_TYPES.MASTERY_TYPE,
    mastery.typeId ?? mastery.masteryTypeId,
    "Service"
  );
  const statusLabel = lookupLabel(
    lookups,
    LOOKUP_TYPES.MASTERY_STATUS,
    mastery.masteryStatuId,
    mastery.masteryStatuId || "—"
  );
  const pricingLabel = lookupLabel(
    lookups,
    LOOKUP_TYPES.PRICING_TYPE,
    mastery.pricingType,
    mastery.pricingType || "—"
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#fafaf9] via-[#f5f5f3] to-[#e8e7e5] dark:from-[#1a1816] dark:via-[#2d2a27] dark:to-[#3a3633]">
      <div className="container-custom py-12">
        {/* Back Button */}
        <motion.button
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-sm text-[#5d5955] dark:text-[#c4bfb9] hover:text-[#6d2842] dark:hover:text-[#e8a0b4] transition-colors mb-8 group">
          <ArrowLeft
            size={16}
            className="group-hover:-translate-x-1 transition-transform"
          />
          {t("masteryInfo.backToMasteries")}
        </motion.button>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Left Side Image - FIXED: Now uses the Gallery component */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}>
            <Gallery
              photoUrls={mastery.photoUrls || []}
              photoEmptyLabel={t("masteryInfo.noImageAvailable")}
              galleryEmptyLabel={t("masteryInfo.noImagesAvailable")}
            />
          </motion.div>

          {/* Right Side Content */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="flex flex-col gap-6">
            {/* Badges */}
            <div className="flex flex-wrap gap-2">
              <Badge color="green">
                <CheckCircle size={12} />
                {statusLabel}
              </Badge>
              <Badge color="primary">
                <Briefcase size={12} />
                {pricingLabel}
              </Badge>
            </div>
            {/* Title */}
            <div>
              <h1 className="text-4xl md:text-5xl font-display font-bold mb-3 text-[#1a1816] dark:text-[#f0ece8]">
                {mastery.title}
              </h1>
              <p className="text-3xl font-bold bg-gradient-to-r from-[#6d2842] via-[#8b3654] to-[#a64d6d] bg-clip-text text-transparent">
                {mastery.price} MAD
              </p>
            </div>
            {/* Description */}
            <div className="glass dark:glass-dark rounded-2xl p-5">
              <h3 className="font-semibold text-lg mb-3">{t("masteryInfo.about")}</h3>
              <p className="text-[#5d5955] dark:text-[#c4bfb9] leading-relaxed">
                {mastery.description}
              </p>
            </div>
            {/* Master Information */}
            <div className="glass dark:glass-dark rounded-2xl p-5">
              <h3 className="font-semibold text-lg mb-4">{t("masteryInfo.masterInformation")}</h3>
              <div className="flex justify-between items-center py-3 border-b border-[#e8e7e5] dark:border-[#3a3633] last:border-0">
                <span className="text-sm text-[#8a8580] dark:text-[#7a756f]">
                  {t("masteryInfo.master")}
                </span>
                <button
                  type="button"
                  onClick={() =>
                    navigate(`/Masterys/history/${mastery.masterId}`)
                  }
                  className="text-sm font-medium text-[#6d2842] dark:text-[#a4c9b3] underline">
                  {mastery.masterName}
                </button>
              </div>
              <InfoRow label={t("masteryInfo.masterId")} value={mastery.masterId} />
              <InfoRow label={t("masteryInfo.phone")} value={mastery.masterPhone} />
              <InfoRow label={t("masteryInfo.city")} value={mastery.city} />
              <InfoRow
                label={t("masteryInfo.experience")}
                value={`${mastery.experienceYears} ${t("masteryInfo.years")}`}
              />
              <InfoRow label={t("masteryInfo.pricingType")} value={pricingLabel} />
              <InfoRow label={t("masteryInfo.status")} value={statusLabel} />
            </div>
            {/* Highlights */}
            <div className="grid grid-cols-2 gap-4">
              <div className="glass dark:glass-dark rounded-xl p-4 text-center">
                <Award size={22} className="mx-auto mb-2 text-[#6d2842]" />
                <p className="text-lg font-bold">{mastery.experienceYears}</p>
                <p className="text-xs text-[#8a8580]">{t("masteryInfo.yearsExperience")}</p>
              </div>
              <div className="glass dark:glass-dark rounded-xl p-4 text-center">
                <MapPin size={22} className="mx-auto mb-2 text-[#6d2842]" />
                <p className="text-lg font-bold">{mastery.city}</p>
                <p className="text-xs text-[#8a8580]">{t("masteryInfo.serviceLocation")}</p>
              </div>
            </div>

            <BookingCalendar resourceType="MASTERY" resourceId={mastery.id} title={t("masteryInfo.bookingCalendar")} quantityEnabled={false} />

            {/* Actions */}

            <ContactButton
              resourceType="MASTERY" // or "MASTERY" or "DEMANDE"
              resourceId={mastery.id}
              initialMessage={`Bonjour, je suis intéressé(e) par votre service de ${mastery.title}.`}
            />
            <div className="flex gap-3 mt-auto">
              <a
                href={`tel:${mastery.masterPhone}`}
                className="flex-1 flex items-center justify-center gap-2 bg-gradient-to-r from-[#6d2842] via-[#8b3654] to-[#a64d6d] text-white font-semibold py-3.5 rounded-xl hover:opacity-90 active:scale-95 transition-all shadow-lg shadow-[#6d2842]/20">
                <Phone size={18} /> {t("masteryInfo.contactMaster")}
              </a>
              <button
                onClick={handleToggleFavorite}
                disabled={favLoading}
                className={`p-3.5 rounded-xl border transition-all ${
                  isLiked
                    ? "bg-[#6d2842] border-[#6d2842] text-white"
                    : "border-[#d4cfc9] dark:border-[#4a4642] text-[#5d5955] dark:text-[#c4bfb9] hover:border-[#6d2842] hover:text-[#6d2842]"
                }`}>
                <Heart size={18} fill={isLiked ? "currentColor" : "none"} />
              </button>
              <button className="p-3.5 rounded-xl border border-[#d4cfc9] dark:border-[#4a4642] text-[#5d5955] dark:text-[#c4bfb9] hover:border-[#6d2842] hover:text-[#6d2842] transition-all">
                <Share2 size={18} />
              </button>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default MasteryInfos;
